<?php
Kirki::add_field( 'oberon', [
	'type'        => 'color',
	'settings'    => 'field_text_color',
	'label'       => __( 'Text Color', 'kirki' ),
	'section'     => 'fields',
	'default'     => '#222222',
  'transport' =>   'auto',
	'priority'    => 130,
  'output'      => [
    [
      'element' => 'input[type=color],
			input[type=date],
			input[type=datetime],
			input[type=datetime-local],
			input[type=email],
			input[type=month],
			input[type=number],
			input[type=password],
			input[type=range],
			input[type=search],
			input[type=tel],
			input[type=text],
			input[type=time],
			input[type=url],
			input[type=week],
			textarea, select',
      'property' => 'color',
    ],
  ],
] );

Kirki::add_field( 'oberon', [
	'type'        => 'color',
	'settings'    => 'field_background_color',
	'label'       => __( 'Background Color', 'kirki' ),
	// 'description' => esc_html__( 'This is a color control - without alpha channel.', 'kirki' ),
	'section'     => 'fields',
	'priority'    => 140,
	'default'     => '#fafafa',
  'transport' =>  "auto",
  'output'      => [
    [
      'element' => 'input[type=color],
										input[type=date],
										input[type=datetime],
										input[type=datetime-local],
										input[type=email],
										input[type=month],
										input[type=number],
										input[type=password],
										input[type=range],
										input[type=search],
										input[type=tel],
										input[type=text],
										input[type=time],
										input[type=url],
										input[type=week],
										 textarea, select,
										 .select2-results__option[aria-selected=true],
										 .select2-container--default .select2-results__option[data-selected=true]',
      'property' => 'background-color',
    ],
  ],
] );

Kirki::add_field( 'oberon', [
	'type'        => 'color',
	'settings'    => 'field_border_color',
	'label'       => __( 'Border Color', 'kirki' ),
	// 'description' => esc_html__( 'This is a color control - without alpha channel.', 'kirki' ),
	'section'     => 'fields',
	'priority'    => 150,
	'default'     => '#cccccc',
  'transport' =>  "auto",
  'output'      => [
    [
      'element' => 'input[type=color],
										input[type=date],
										input[type=datetime],
										input[type=datetime-local],
										input[type=email],
										input[type=month],
										input[type=number],
										input[type=password],
										input[type=range],
										input[type=search],
										input[type=tel],
										input[type=text],
										input[type=time],
										input[type=url],
										input[type=week],
										textarea, select,
										span.select2-dropdown,
										.select2-container--default .select2-search--dropdown .select2-search__field',
      'property' => 'border-color',
    ],
  ],
] );

// Hover

Kirki::add_field( 'oberon', [
	'type'        => 'color',
	'settings'    => 'field_text_color_hover',
	'label'       => __( 'Text Color', 'kirki' ),
	// 'description' => esc_html__( 'This is a color control - without alpha channel.', 'kirki' ),
	'section'     => 'fields',
	'priority'    => 170,
	'default'     => '#000000',
  'transport' =>  "auto",
  'output'      => [
    [
      'element' => 'input[type=color]:focus,
										input[type=date]:focus,
										input[type=datetime]:focus,
										input[type=datetime-local]:focus,
										input[type=email]:focus,
										input[type=month]:focus,
										input[type=number]:focus,
										input[type=password]:focus,
										input[type=range]:focus,
										input[type=search]:focus,
										input[type=tel]:focus,
										input[type=text]:focus,
										input[type=time]:focus,
										input[type=url]:focus,
										input[type=week]:focus,
										textarea:focus,
										select:focus,
										.woocommerce .select2-container--default .select2-selection--single .select2-selection__rendered,
										span.select2-search,
										.select2-container li.select2-results__option',
      'property' => 'color',
    ],
  ],
] );

Kirki::add_field( 'oberon', [
	'type'        => 'color',
	'settings'    => 'field_background_color_hover',
	'label'       => __( 'Background Color', 'kirki' ),
	// 'description' => esc_html__( 'This is a color control - without alpha channel.', 'kirki' ),
	'section'     => 'fields',
	'priority'    => 180,
	'default'     => '#fbfbfb',
  'transport' =>  "auto",
  'output'      => [
    [
			'element' => 'input[type=color]:focus,
										input[type=date]:focus,
										input[type=datetime]:focus,
										input[type=datetime-local]:focus,
										input[type=email]:focus,
										input[type=month]:focus,
										input[type=number]:focus,
										input[type=password]:focus,
										input[type=range]:focus,
										input[type=search]:focus,
										input[type=tel]:focus,
										input[type=text]:focus,
										input[type=time]:focus,
										input[type=url]:focus,
										input[type=week]:focus,
										textarea:focus,
										select:focus,
										.woocommerce .select2-container--default,
										.woocommerce .select2-selection--single,
										span.select2-dropdown,
										span.select2-search,
										.select2-container li.select2-results__option',
	      'property' => 'background-color',
    ],
  ],
] );

Kirki::add_field( 'oberon', [
	'type'        => 'color',
	'settings'    => 'field_border_color_hover',
	'label'       => __( 'Border Color', 'kirki' ),
	// 'description' => esc_html__( 'This is a color control - without alpha channel.', 'kirki' ),
	'section'     => 'fields',
	'priority'    => 190,
	'default'     => '#aaaaaa',
  'transport' =>  "auto",
  'output'      => [
    [
			'element' => 'input[type=color]:focus,
										input[type=date]:focus,
										input[type=datetime]:focus,
										input[type=datetime-local]:focus,
										input[type=email]:focus,
										input[type=month]:focus,
										input[type=number]:focus,
										input[type=password]:focus,
										input[type=range]:focus,
										input[type=search]:focus,
										input[type=tel]:focus,
										input[type=text]:focus,
										input[type=time]:focus,
										input[type=url]:focus,
										input[type=week]:focus,
										textarea:focus,
										select:focus,
										.woocommerce .select2-container--default,
										.woocommerce .select2-selection--single',
      'property' => 'border-color',
    ],
  ],
] );

////////
Kirki::add_field( 'oberon', [
	'type'        => 'slider',
	'settings'    => 'field_padding',
	'label'       => esc_html__( 'Padding (top & bottom)', 'kirki' ),
	'section'     => 'fields',
	'default'     => 10,
	'choices'     => [
		'min'  => 0,
		'max'  => 30,
		'step' => 2,
	],
  'output' => [
    [
      'element' => 'input[type=color],
										input[type=date],
										input[type=datetime],
										input[type=datetime-local],
										input[type=email],
										input[type=month],
										input[type=number],
										input[type=password],
										input[type=range],
										input[type=search],
										input[type=tel],
										input[type=text],
										input[type=time],
										input[type=url],
										input[type=week],
										textarea, select,
										.select2-container--default .select2-selection--single',
      'property' => 'padding-top',
      'units'    => 'px',
    ],
    [
      'element' => 'input[type=color],
										input[type=date],
										input[type=datetime],
										input[type=datetime-local],
										input[type=email],
										input[type=month],
										input[type=number],
										input[type=password],
										input[type=range],
										input[type=search],
										input[type=tel],
										input[type=text],
										input[type=time],
										input[type=url],
										input[type=week],
										textarea, select,
										.select2-container--default .select2-selection--single',
      'property' => 'padding-bottom',
      'units'    => 'px',
    ],
  ],
  'transport' =>  "auto",
] );

Kirki::add_field( 'oberon', [
	'type'        => 'slider',
	'settings'    => 'field_padding_sides',
	'label'       => esc_html__( 'Padding (left & right)', 'kirki' ),
	'section'     => 'fields',
	'priority'    => 210,
	'default'     => 12,
	'choices'     => [
		'min'  => 0,
		'max'  => 50,
		'step' => 2,
	],
  'output' => [
    [
      'element' => 'input[type=color],
										input[type=date],
										input[type=datetime],
										input[type=datetime-local],
										input[type=email],
										input[type=month],
										input[type=number],
										input[type=password],
										input[type=range],
										input[type=search],
										input[type=tel],
										input[type=text],
										input[type=time],
										input[type=url],
										input[type=week],
										textarea, select',
      'property' => 'padding-left',
      'units'    => 'px',
    ],
    [
      'element' => 'input[type=color],
										input[type=date],
										input[type=datetime],
										input[type=datetime-local],
										input[type=email],
										input[type=month],
										input[type=number],
										input[type=password],
										input[type=range],
										input[type=search],
										input[type=tel],
										input[type=text],
										input[type=time],
										input[type=url],
										input[type=week],
										textarea, select',
      'property' => 'padding-right',
      'units'    => 'px',
    ],
  ],
  'transport' =>  "auto",
] );

Kirki::add_field( 'oberon', [
	'type'        => 'slider',
	'settings'    => 'field_border_width',
	'label'       => esc_html__( 'Border Width', 'kirki' ),
	'section'     => 'fields',
	'priority'    => 220,
	'default'     => 1,
	'choices'     => [
		'min'  => 0,
		'max'  => 10,
		'step' => 1,
	],
  'output' => [
    [
      'element' => 'input[type=color],
										input[type=date],
										input[type=datetime],
										input[type=datetime-local],
										input[type=email],
										input[type=month],
										input[type=number],
										input[type=password],
										input[type=range],
										input[type=search],
										input[type=tel],
										input[type=text],
										input[type=time],
										input[type=url],
										input[type=week],
										textarea, select,
										.select2-container--default .select2-selection--single',
      'property' => 'border-width',
      'units'    => 'px',
    ],
  ],
  'transport' =>  "auto",
] );

Kirki::add_field( 'oberon', [
	'type'        => 'slider',
	'settings'    => 'field_border_radius_setting',
	'label'       => esc_html__( 'Rounded Corners', 'kirki' ),
	'section'     => 'fields',
	'priority'    => 230,
	'default'     => 0,
	'choices'     => [
		'min'  => 0,
		'max'  => 30,
		'step' => 0,
	],
  'output' => [
    [
      'element' => 'input[type=color],
										input[type=date],
										input[type=datetime],
										input[type=datetime-local],
										input[type=email],
										input[type=month],
										input[type=number],
										input[type=password],
										input[type=range],
										input[type=search],
										input[type=tel],
										input[type=text],
										input[type=time],
										input[type=url],
										input[type=week],
										textarea, select,
										.select2-container--default .select2-selection--single',
      'property' => 'border-radius',
      'units'    => 'px',
    ],
  ],
  'transport' =>  "auto",
] );
